# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Compile AoT (MacOS-Arm64)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    # Only run this workflow if the last commit message starts with 'Update Version'
    # This is useful to avoid running the workflow on every commit
    # Just make sure to push all commits immediately authoring 'Update Version'
    if: startsWith(github.event.head_commit.message, 'Update Version')

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Release
      run: dotnet publish -r osx-arm64 -c Release
